#%RAML 1.0 DataType
type: object
properties:
  id:
    type: string
    example: "102"
  firstName:
    type: string
    example: "vivek"
  lastName:
    type: string
    example: "sharma"  
  email:
    type: string
    example: "sharma@gmail.com"
  country:
    type: string
    example: "India"
  address:
    type: string
    example: "122,xyz city"    